language: python
python:
- 3.3
- 3.4
- 3.5
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source sismic -m unittest discover
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: AlexandreDecan
  password:
    secure: nwg7qvFugKVDvh2hSzMDD4H2OsHn8ySbM2bKWTBLxUXm0AHB5yoFZGgYumIfnq/NJnurv9NhU3oVFvOW7Tll5VktPfKrMG1MsUFvivFIYlzT7MdwiInjiPKuNJnyRuNqGQBUdJueuDv3Z7Yc0ebZXCBEvjRDxH111TiNt0MiqMy/obFjuONVvED+BBTdRwcYG9SPMavtP8AF1yy5m2V3J5W095TNcz+zcEkSG2BAp3m9W+ZSUpjFF5AaxgWQDb4lz5G8FOrsTq3Kt8X501rC+zizwPfbStJ80UlCWrfClNnN3GI0LZ7x9NuO2rC/FM2WZ4jQaeS5X9Hu3oUvLSZCxS5/+cB7AUhL1l1kpgFq5xDBKmUo3vSIudc/mThFV5kB/mWnEkU2PBcMitRVXtqOWPPSWSOqFizCUAIltqbTl78IfjwVqPaVLzkaQsVMN5lIDVsJTKcl+UdpSZIm9r2pF6R6Z8Uu2duH9PLimKE71e57gEyFrw622sQMBkE8CQK0uafUUNQchDOf/2VZ07spBeorpUD1m4848zrkCHimOzBjLoUL5BUqs+xzX0REOKqBP0aNBEZZNOR5Hb1ChutLg6h5XNpeg8bd41QXuy0pzxHNXUrvtoJcvf36Z9Mw/2WxZyPIjNw7o2a7xcno1YHuPCEKZCz88rUw6MRuRvrR5sM=
  on:
    branch: stable
    python: '3.4'
