name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pip -U
          pip install -e . --ignore-requires-python
      - name: Install test dependencies
        run:  |
          pip install coverage
          pip install -r requirements.txt
      - name: Execute tests
        run: coverage run --source sismic -m pytest tests
      - name: Execute documentation
        run : |
          cd docs
          make doctest
          cd ..

          cd docs/examples/microwave/
          python -m unittest
          cd ../../..
      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github
